//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_cus_base
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(40)]
    	public virtual string cus_no
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(200)]
    	public virtual string cus_name
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(100)]
    	public virtual string cus_sname
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> cus_lastid
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(50)]
    	public virtual string cus_tel
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string cus_city
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(255)]
    	public virtual string cus_address
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string cus_note
        {
            get;
            set;
        }
    	[Required]
    	public virtual int con_id
        {
            get;
            set;
        }
    	[Required]
    	public virtual int user_id
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(255)]
    	public virtual string con_team
        {
            get;
            set;
        }
    	[Required]
    	public virtual int con_is_pub
        {
            get;
            set;
        }
    	[Required]
    	public virtual int con_back
        {
            get;
            set;
        }

        #endregion
    }
}
