//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_cus_log
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
    	public virtual int cus_id
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(50)]
    	public virtual string cus_type
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string cus_info
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> user_id
        {
            get;
            set;
        }
    	[Required]
    	public virtual System.DateTime cus_addtime
        {
            get;
            set;
        }

        #endregion
    }
}
