//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_fun_expand
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
    	public virtual int myapp_id
        {
            get { return _myapp_id; }
            set
            {
                if (_myapp_id != value)
                {
                    if (T_fun_myapp != null && T_fun_myapp.id != value)
                    {
                        T_fun_myapp = null;
                    }
                    _myapp_id = value;
                }
            }
        }
        private int _myapp_id;
    	[Required]
        [MaxLength(50)]
    	public virtual string exp_name
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(50)]
    	public virtual string exp_title
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(50)]
    	public virtual string exp_ctype
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(50)]
    	public virtual string exp_dtype
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> exp_length
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string exp_place
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_option
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_default
        {
            get;
            set;
        }
    	[Required]
    	public virtual int exp_is_null
        {
            get;
            set;
        }
    	[Required]
    	public virtual int exp_is_pw
        {
            get;
            set;
        }
    	[Required]
    	public virtual int exp_is_html
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> exp_etype
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_tipmsg
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_errmsg
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_pattern
        {
            get;
            set;
        }
    	//[Required]
    	public virtual string exp_sortid
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(100)]
    	public virtual string exp_css
        {
            get;
            set;
        }
    	[Required]
    	public virtual int exp_is_sys
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual T_fun_myapp T_fun_myapp
        {
            get { return _t_fun_myapp; }
            set
            {
                if (!ReferenceEquals(_t_fun_myapp, value))
                {
                    var previousValue = _t_fun_myapp;
                    _t_fun_myapp = value;
                    FixupT_fun_myapp(previousValue);
                }
            }
        }
        private T_fun_myapp _t_fun_myapp;

        #endregion
        #region Association Fixup
    
        private void FixupT_fun_myapp(T_fun_myapp previousValue)
        {
            if (previousValue != null && previousValue.T_fun_expand.Contains(this))
            {
                previousValue.T_fun_expand.Remove(this);
            }
    
            if (T_fun_myapp != null)
            {
                if (!T_fun_myapp.T_fun_expand.Contains(this))
                {
                    T_fun_myapp.T_fun_expand.Add(this);
                }
                if (myapp_id != T_fun_myapp.id)
                {
                    myapp_id = T_fun_myapp.id;
                }
            }
        }

        #endregion
    }
}
