//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_sys_department
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
    	public virtual int parent_id
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(200)]
    	public virtual string dep_name
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> dep_num
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(255)]
    	public virtual string dep_respon
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(255)]
    	public virtual string dep_skills
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(255)]
    	public virtual string dep_note
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<T_sys_user> T_sys_user
        {
            get
            {
                if (_t_sys_user == null)
                {
                    var newCollection = new FixupCollection<T_sys_user>();
                    newCollection.CollectionChanged += FixupT_sys_user;
                    _t_sys_user = newCollection;
                }
                return _t_sys_user;
            }
            set
            {
                if (!ReferenceEquals(_t_sys_user, value))
                {
                    var previousValue = _t_sys_user as FixupCollection<T_sys_user>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupT_sys_user;
                    }
                    _t_sys_user = value;
                    var newValue = value as FixupCollection<T_sys_user>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupT_sys_user;
                    }
                }
            }
        }
        private ICollection<T_sys_user> _t_sys_user;

        #endregion
        #region Association Fixup
    
        private void FixupT_sys_user(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (T_sys_user item in e.NewItems)
                {
                    item.T_sys_department = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (T_sys_user item in e.OldItems)
                {
                    if (ReferenceEquals(item.T_sys_department, this))
                    {
                        item.T_sys_department = null;
                    }
                }
            }
        }

        #endregion
    }
}
