//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_sys_role
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(30)]
    	public virtual string role_name
        {
            get;
            set;
        }
    	[Required]
    	public virtual int role_type
        {
            get;
            set;
        }
    	[Required]
    	public virtual int pow_id
        {
            get { return _pow_id; }
            set
            {
                if (_pow_id != value)
                {
                    if (T_sys_power != null && T_sys_power.id != value)
                    {
                        T_sys_power = null;
                    }
                    _pow_id = value;
                }
            }
        }
        private int _pow_id;
    	[Required]
        [MaxLength(200)]
    	public virtual string role_date
        {
            get;
            set;
        }
    	[Required]
    	public virtual int role_issys
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual T_sys_power T_sys_power
        {
            get { return _t_sys_power; }
            set
            {
                if (!ReferenceEquals(_t_sys_power, value))
                {
                    var previousValue = _t_sys_power;
                    _t_sys_power = value;
                    FixupT_sys_power(previousValue);
                }
            }
        }
        private T_sys_power _t_sys_power;
    
        public virtual ICollection<T_sys_user> T_sys_user
        {
            get
            {
                if (_t_sys_user == null)
                {
                    var newCollection = new FixupCollection<T_sys_user>();
                    newCollection.CollectionChanged += FixupT_sys_user;
                    _t_sys_user = newCollection;
                }
                return _t_sys_user;
            }
            set
            {
                if (!ReferenceEquals(_t_sys_user, value))
                {
                    var previousValue = _t_sys_user as FixupCollection<T_sys_user>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupT_sys_user;
                    }
                    _t_sys_user = value;
                    var newValue = value as FixupCollection<T_sys_user>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupT_sys_user;
                    }
                }
            }
        }
        private ICollection<T_sys_user> _t_sys_user;

        #endregion
        #region Association Fixup
    
        private void FixupT_sys_power(T_sys_power previousValue)
        {
            if (previousValue != null && previousValue.T_sys_role.Contains(this))
            {
                previousValue.T_sys_role.Remove(this);
            }
    
            if (T_sys_power != null)
            {
                if (!T_sys_power.T_sys_role.Contains(this))
                {
                    T_sys_power.T_sys_role.Add(this);
                }
                if (pow_id != T_sys_power.id)
                {
                    pow_id = T_sys_power.id;
                }
            }
        }
    
        private void FixupT_sys_user(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (T_sys_user item in e.NewItems)
                {
                    item.T_sys_role = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (T_sys_user item in e.OldItems)
                {
                    if (ReferenceEquals(item.T_sys_role, this))
                    {
                        item.T_sys_role = null;
                    }
                }
            }
        }

        #endregion
    }
}
