//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_sys_power
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
    	public virtual int module
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(200)]
    	public virtual string power_nav
        {
            get;
            set;
        }
    	[Required]
    	public virtual byte[] power_action
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<T_sys_role> T_sys_role
        {
            get
            {
                if (_t_sys_role == null)
                {
                    var newCollection = new FixupCollection<T_sys_role>();
                    newCollection.CollectionChanged += FixupT_sys_role;
                    _t_sys_role = newCollection;
                }
                return _t_sys_role;
            }
            set
            {
                if (!ReferenceEquals(_t_sys_role, value))
                {
                    var previousValue = _t_sys_role as FixupCollection<T_sys_role>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupT_sys_role;
                    }
                    _t_sys_role = value;
                    var newValue = value as FixupCollection<T_sys_role>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupT_sys_role;
                    }
                }
            }
        }
        private ICollection<T_sys_role> _t_sys_role;

        #endregion
        #region Association Fixup
    
        private void FixupT_sys_role(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (T_sys_role item in e.NewItems)
                {
                    item.T_sys_power = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (T_sys_role item in e.OldItems)
                {
                    if (ReferenceEquals(item.T_sys_power, this))
                    {
                        item.T_sys_power = null;
                    }
                }
            }
        }

        #endregion
    }
}
