//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel.DataAnnotations;

namespace teaCRM.Model
{
    public partial class T_sys_user
    {
        #region Primitive Properties
    	[Required]
    	public virtual int id
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(30)]
    	public virtual string user_lname
        {
            get;
            set;
        }
    	[Required]
        [MaxLength(30)]
    	public virtual string user_password
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string user_tname
        {
            get;
            set;
        }
    	[Required]
    	public virtual int user_sex
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string user_phone
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(50)]
    	public virtual string user_e_mail
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string user_tel
        {
            get;
            set;
        }
    	//[Required]
        [MaxLength(20)]
    	public virtual string user_qq
        {
            get;
            set;
        }
    	[Required]
    	public virtual int dep_id
        {
            get { return _dep_id; }
            set
            {
                if (_dep_id != value)
                {
                    if (T_sys_department != null && T_sys_department.id != value)
                    {
                        T_sys_department = null;
                    }
                    _dep_id = value;
                }
            }
        }
        private int _dep_id;
    	//[Required]
        [MaxLength(30)]
    	public virtual string user_position
        {
            get;
            set;
        }
    	//[Required]
    	public virtual Nullable<int> user_jobstatus
        {
            get;
            set;
        }
    	[Required]
    	public virtual int role_id
        {
            get { return _role_id; }
            set
            {
                if (_role_id != value)
                {
                    if (T_sys_role != null && T_sys_role.id != value)
                    {
                        T_sys_role = null;
                    }
                    _role_id = value;
                }
            }
        }
        private int _role_id;
    	[Required]
    	public virtual int user_enable
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual T_sys_department T_sys_department
        {
            get { return _t_sys_department; }
            set
            {
                if (!ReferenceEquals(_t_sys_department, value))
                {
                    var previousValue = _t_sys_department;
                    _t_sys_department = value;
                    FixupT_sys_department(previousValue);
                }
            }
        }
        private T_sys_department _t_sys_department;
    
        public virtual T_sys_role T_sys_role
        {
            get { return _t_sys_role; }
            set
            {
                if (!ReferenceEquals(_t_sys_role, value))
                {
                    var previousValue = _t_sys_role;
                    _t_sys_role = value;
                    FixupT_sys_role(previousValue);
                }
            }
        }
        private T_sys_role _t_sys_role;

        #endregion
        #region Association Fixup
    
        private void FixupT_sys_department(T_sys_department previousValue)
        {
            if (previousValue != null && previousValue.T_sys_user.Contains(this))
            {
                previousValue.T_sys_user.Remove(this);
            }
    
            if (T_sys_department != null)
            {
                if (!T_sys_department.T_sys_user.Contains(this))
                {
                    T_sys_department.T_sys_user.Add(this);
                }
                if (dep_id != T_sys_department.id)
                {
                    dep_id = T_sys_department.id;
                }
            }
        }
    
        private void FixupT_sys_role(T_sys_role previousValue)
        {
            if (previousValue != null && previousValue.T_sys_user.Contains(this))
            {
                previousValue.T_sys_user.Remove(this);
            }
    
            if (T_sys_role != null)
            {
                if (!T_sys_role.T_sys_user.Contains(this))
                {
                    T_sys_role.T_sys_user.Add(this);
                }
                if (role_id != T_sys_role.id)
                {
                    role_id = T_sys_role.id;
                }
            }
        }

        #endregion
    }
}
