//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;



namespace teaCRM.Model
{
    public partial class teaCRMEntities : ObjectContext
    {
        public const string ConnectionString = "name=teaCRMEntities";
        public const string ContainerName = "teaCRMEntities";
    
        #region Constructors
    
        public teaCRMEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public teaCRMEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public teaCRMEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<T_con_expvalue> T_con_expvalue
        {
            get { return _t_con_expvalue  ?? (_t_con_expvalue = CreateObjectSet<T_con_expvalue>("T_con_expvalue")); }
        }
        private ObjectSet<T_con_expvalue> _t_con_expvalue;
    
        public ObjectSet<T_cus_base> T_cus_base
        {
            get { return _t_cus_base  ?? (_t_cus_base = CreateObjectSet<T_cus_base>("T_cus_base")); }
        }
        private ObjectSet<T_cus_base> _t_cus_base;
    
        public ObjectSet<T_cus_con> T_cus_con
        {
            get { return _t_cus_con  ?? (_t_cus_con = CreateObjectSet<T_cus_con>("T_cus_con")); }
        }
        private ObjectSet<T_cus_con> _t_cus_con;
    
        public ObjectSet<T_cus_expvalue> T_cus_expvalue
        {
            get { return _t_cus_expvalue  ?? (_t_cus_expvalue = CreateObjectSet<T_cus_expvalue>("T_cus_expvalue")); }
        }
        private ObjectSet<T_cus_expvalue> _t_cus_expvalue;
    
        public ObjectSet<T_cus_log> T_cus_log
        {
            get { return _t_cus_log  ?? (_t_cus_log = CreateObjectSet<T_cus_log>("T_cus_log")); }
        }
        private ObjectSet<T_cus_log> _t_cus_log;
    
        public ObjectSet<T_fun_app> T_fun_app
        {
            get { return _t_fun_app  ?? (_t_fun_app = CreateObjectSet<T_fun_app>("T_fun_app")); }
        }
        private ObjectSet<T_fun_app> _t_fun_app;
    
        public ObjectSet<T_fun_expand> T_fun_expand
        {
            get { return _t_fun_expand  ?? (_t_fun_expand = CreateObjectSet<T_fun_expand>("T_fun_expand")); }
        }
        private ObjectSet<T_fun_expand> _t_fun_expand;
    
        public ObjectSet<T_fun_filters> T_fun_filters
        {
            get { return _t_fun_filters  ?? (_t_fun_filters = CreateObjectSet<T_fun_filters>("T_fun_filters")); }
        }
        private ObjectSet<T_fun_filters> _t_fun_filters;
    
        public ObjectSet<T_fun_myapp> T_fun_myapp
        {
            get { return _t_fun_myapp  ?? (_t_fun_myapp = CreateObjectSet<T_fun_myapp>("T_fun_myapp")); }
        }
        private ObjectSet<T_fun_myapp> _t_fun_myapp;
    
        public ObjectSet<T_fun_operating> T_fun_operating
        {
            get { return _t_fun_operating  ?? (_t_fun_operating = CreateObjectSet<T_fun_operating>("T_fun_operating")); }
        }
        private ObjectSet<T_fun_operating> _t_fun_operating;
    
        public ObjectSet<T_fun_tags> T_fun_tags
        {
            get { return _t_fun_tags  ?? (_t_fun_tags = CreateObjectSet<T_fun_tags>("T_fun_tags")); }
        }
        private ObjectSet<T_fun_tags> _t_fun_tags;
    
        public ObjectSet<T_sys_department> T_sys_department
        {
            get { return _t_sys_department  ?? (_t_sys_department = CreateObjectSet<T_sys_department>("T_sys_department")); }
        }
        private ObjectSet<T_sys_department> _t_sys_department;
    
        public ObjectSet<T_sys_log> T_sys_log
        {
            get { return _t_sys_log  ?? (_t_sys_log = CreateObjectSet<T_sys_log>("T_sys_log")); }
        }
        private ObjectSet<T_sys_log> _t_sys_log;
    
        public ObjectSet<T_sys_power> T_sys_power
        {
            get { return _t_sys_power  ?? (_t_sys_power = CreateObjectSet<T_sys_power>("T_sys_power")); }
        }
        private ObjectSet<T_sys_power> _t_sys_power;
    
        public ObjectSet<T_sys_role> T_sys_role
        {
            get { return _t_sys_role  ?? (_t_sys_role = CreateObjectSet<T_sys_role>("T_sys_role")); }
        }
        private ObjectSet<T_sys_role> _t_sys_role;
    
        public ObjectSet<T_sys_user> T_sys_user
        {
            get { return _t_sys_user  ?? (_t_sys_user = CreateObjectSet<T_sys_user>("T_sys_user")); }
        }
        private ObjectSet<T_sys_user> _t_sys_user;
    
        public ObjectSet<V_cus_info> V_cus_info
        {
            get { return _v_cus_info  ?? (_v_cus_info = CreateObjectSet<V_cus_info>("V_cus_info")); }
        }
        private ObjectSet<V_cus_info> _v_cus_info;

        #endregion
    }
}
